quizes/urls.py
from django.urls import path

from .views import Quiz, ViewQuizResults


urlpatterns = [
    path('', Quiz.as_view(), name='quiz'),
    path('view_results/', ViewQuizResults.as_view(), name='view-results-of-quiz'),
]

src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

from .views import AboutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', AboutView.as_view(), name='about-site'),
    path('articles/', include(('articles.urls', 'articles'), namespace='articles')),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('quizes/', include(('quizes.urls', 'quizes'), namespace='quizes')),
]


if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

    urlpatterns += static(
        settings.MEDIA_URL, document_root = settings.MEDIA_ROOT
    )

quizes/models.py
from django.db import models

from articles.models import Article


class Quiz(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    number_of_questions = models.PositiveSmallIntegerField()

    def __str__(self):
        return self.article.title

    def get_question(self):
        return self.question_set.all()


class Question(models.Model): 
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    text = models.CharField(max_length=500)

    def __str__(self):
        return self.text

    def get_answers(self):
        return self.answer_set.all()

    def get_correct_answer(self):
        return self.answer_set.all()

class Answer(models.Model):
    text = models.CharField(max_length=500)
    correct = models.BooleanField(default=False)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    def __str__(self):
        return f'вопрос: {self.question.text}, ответ: {self.text}, правильный: {self.correct}'


class Results(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    user = models.ForeignKey
    score = models.PositiveSmallIntegerField()

    def __str__(self):
        return self.pk

quizes/forms.py
from django import forms

from .models import Quiz


class QuizForm(forms.Form):
    articles = forms.ModelMultipleChoiceField(
        label="Выберите статьи для теста", 
        queryset=Quiz.objects.all(),
        widget=forms.SelectMultiple(
            attrs={
                'class': 'form-control js-example-basic-multiple'
            }
        )
    )
    quantity_questions = forms.IntegerField(
        label="Введите кол-во вопросов которые хотите прорешать.", 
        min_value=1,
        widget=forms.NumberInput(
            attrs={
                'class': 'form-control',
            }
        )
    ) 

quizes/views.py
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.contrib import messages 
from django.shortcuts import render
from django.views.generic import FormView

from .forms import QuizForm 
from .services import get_questions, results_of_quiz

import json


class Quiz(FormView):
    form_class = QuizForm
    template_name = 'quizes/create_quiz.html'
    context_object_name = 'questions'

    def post(self, request, template_name='quizes/create_quiz.html'):
        form = QuizForm(request.POST)
        
        if form.is_valid():
            try:
                context = get_questions(request, form)
            except ValueError as e:
                messages.error(self.request, e)
                return render(request, template_name, {'form': form})
            return render(request, template_name='quizes/created_quiz.html', context=context)
        return render(request, template_name, {'form': form})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class ViewQuizResults(FormView):
    form_class = QuizForm
    template_name = 'quizes/view_results.html'
    context_object_name = 'questions'

    def post(self, *args, **kwargs):
        if self.request.method == "POST":
            list_of_answers = json.loads(self.request.POST.dict()['list_of_answers'])
            res_of_quiz, right_answ, total_questions = results_of_quiz(list_of_answers) 
            html = render_to_string('quizes/view_results.html', {'res_of_quiz': res_of_quiz,'right_answ': right_answ, 'total_questions': total_questions})
            return JsonResponse(html, safe=False)

        return JsonResponse({"error": ""}, status=400)

quizes/templates/quizes/create_quiz.html
{% extends 'base.html' %}

{% block title %} 
    Tecт
{% endblock %}

{% block content %}
    <br>
    <br>
        <div class="row">
            <div class="col-md-8 mx-auto">
                <h1> Проверка знаний  </h1>
                <form action="" method="post">

                    {% csrf_token %}

                    {{ form.as_p }}

                    <button type="submit" class="btn btn-success">
                        Начать
                    </button>
                </form>
            </div>
        </div>
    <br>
    <br>
{% endblock %}

quizes/templates/quizes/created_quiz.html
{% extends 'base.html' %}

{% block title %} 
    Tecт
{% endblock %}

{% block content %}
    
    <div class="quiz">
        <h1> Опрос по статье </h1>

        <hr>
       
        {% for question in questions %}
            <br>
            <br>
            <div name="question" id="{{ question.pk }}">
                <h2> {{ forloop.counter }}) <strong> {{ question }} </strong> </h2>
                    <div class="bd-example" style="padding: 1.5rem;margin: 1rem -.75rem 0;border-width: 1px;border-radius: .50rem;border: solid #dee2e6;">

                        {% for answer in question.get_answers %} 
                            <div class="alert alert-primary" role="alert">
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="answer_to_question_{{question.pk}}" id="{{answer.pk}}-{{question.pk}}">
                                    <label class="form-check-label" for="{{answer.pk}}-{{question.pk}}">
                                        {{ answer.text }}
                                    </label>
                                </div>
                            </div>
                        {% endfor %}

                    </div>
                </div>
            <br>

            
        {% endfor %}

            <button type="button" class="btn btn-primary" onclick="passAnswers()"> 
                Завершить тест 
            </button> 
            <br> 
            <br> 
            <br> 

    </div>

    <script type="text/javascript">
        function passAnswers() {
            let questions = document.getElementsByName("question")
            let answers = []
            for (let i = 0; i < questions.length; i++) {
                let chosen_answer = document.querySelector(`input[name = answer_to_question_${i+1}]:checked`)
                if (chosen_answer) {
                    answers.push([+questions[i].id, +chosen_answer.id.split("-")[0]])
                } else {
                    answers.push([+questions[i].id, 'None'])
                }
            }

            cleaned_data = JSON.stringify(answers)
            $.ajax({
                type: "POST", data: {
                    "list_of_answers": cleaned_data, 
                    "csrfmiddlewaretoken": "{{csrf_token}}"
                },
                url: "{% url 'quizes:view-results-of-quiz' %}",
                dataType: "json",
                success: function (data) {
                    $(".quiz").html(data)
                },
                failure: function () {
                    alert("failure");
                }
            });
        }
    </script>

{% endblock %}

quizes/templates/quizes/view_results.html
{% block content %}
    <br>
    <br>
        <h1> Результаты теста: </h1>
        <br>
         Правильно: {{ right_answ }} из {{ total_questions }}
        <br>
        {% for right_answer, gotten in res_of_quiz %}

            <div class="row">
                <div class="col-md-10 mx-2">

                     
                    <h2>{{ forloop.counter }}) <strong> {{ right_answer.question  }} </strong> </h2>
                    <div class="bd-example" style="padding: 1.5rem;margin: 1rem -.75rem 0;border-width: 1px;border-radius: .50rem;border: solid #dee2e6;">
                            <div class="alert alert-success" role="alert">
                                <strong> Правильный ответ: </strong>
                                        {{ right_answer.text }} 
                            </div>

                            {% if right_answer == gotten %}
                                <div class="alert alert-success" role="alert">
                                    <strong> Ваш ответ: </strong>
                                        {{ gotten.text }} 
                                    <br>
                                </div>
                            {% elif gotten == 'None' %} 
                                <div class="alert alert-danger" role="alert">
                                    <strong> Ваш ответ: </strong>
                                        
                                    <br>
                                </div>
                            {% else %}

                                <div class="alert alert-danger" role="alert">
                                    <strong> Ваш ответ: </strong>
                                        {{ gotten.text }}
                                    <br>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
            <br>
        {% endfor %}
                
                 
    <br>
    <br>
{% endblock %}