accounts/urls.py
from django.urls import path

from accounts.views import UserRegistration, UserAuthentication, logout_view, EditProfile, ViewProfile


urlpatterns = [
    path('registration/', UserRegistration.as_view(), name='registration'),
    path('login/', UserAuthentication.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),

    path('edit-pofile/<slug:username_slug>', EditProfile.as_view(), name='edit-profile'),
    path('view-pofile/<slug:username_slug>', ViewProfile.as_view(), name='view-profile'),
]

articles/urls.py
from django.urls import path
from .views import (
        ArticlesListView, SearchArticle, ViewArticle, AddReviewToArticle , 
        AddLikeToArticle, AddDislikeToArticle, ReplyToReview, AddLikeToReview, AddDislikeToReview 
    )

urlpatterns = [
    path('', ArticlesListView.as_view(), name='view-articles'),
    path('search-article', SearchArticle.as_view(), name='search-article'),

    path('view-article/<slug:article_slug>', ViewArticle.as_view(), name='view-article'),
    path('review-to-article/<slug:article_slug>', AddReviewToArticle.as_view(), name='review-article'),
    path('like-article/<slug:article_slug>', AddLikeToArticle.as_view(), name='like-article'),
    path('dislike-article/<slug:article_slug>', AddDislikeToArticle.as_view(), name='dislike-article'),

    path('add-reply-to-review/<slug:article_slug>/<int:review_pk>', ReplyToReview.as_view(), name='reply-to-review'),
    path('like-review-article/<slug:article_slug>/<int:review_pk>', AddLikeToReview.as_view(), name='like-review'),
    path('dislike-review-article/<slug:article_slug>/<int:review_pk>', AddDislikeToReview.as_view(), name='dislike-review'),
]

quizes/urls.py
from django.urls import path

from .views import Quiz, ViewQuizResults


urlpatterns = [
    path('', Quiz.as_view(), name='quiz'),
    path('view_results/', ViewQuizResults.as_view(), name='view-results-of-quiz'),
]

src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

from .views import AboutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', AboutView.as_view(), name='about-site'),
    path('articles/', include(('articles.urls', 'articles'), namespace='articles')),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('quizes/', include(('quizes.urls', 'quizes'), namespace='quizes')),
]


if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

    urlpatterns += static(
        settings.MEDIA_URL, document_root = settings.MEDIA_ROOT
    )

templates/inc/_messages.html
<div class="container my-4">
  <div class="row">
    <div class="col-md-8 mx-auto">
        {% for message in messages %}
            
            {% if message.tags == 'error' %}

              <div class="alert alert-danger messages alert-dismissible fade show" role="alert">
                  {{ message }}
                  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>

            {% else %}

              <div class="alert alert-{{ message.tags }} messages alert-dismissible fade show" role="alert">
                  {{ message }}
                  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              </div> 
            {% endif %} 
        {% endfor %}
    </div>
  </div>
</div>

templates/inc/_nav.html
{% url 'articles:view-articles' as view_articles_url %}
{% url 'about-site' as about_url %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="#" > History helper </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div id="main-menu" class="collapse navbar-collapse">
        <strong>
      <ul class="navbar-nav">
        <li class="nav-item ">
            <a class="nav-link {%if request.path == view_articles_url  %} active {% endif %}" href="{% url 'articles:view-articles' %}" role="button" aria-expanded="false">Статьи</a>
        </li>
        <li class="nav-item ">
            <a class="nav-link" href="{% url 'quizes:quiz' %}" role="button" aria-expanded="false">Тесты</a>
        </li>
        <li class="nav-item ">
            <a class="nav-link {%if request.path == about_url  %} active {% endif %}" href="{% url 'about-site' %}" aria-current="page" href="#">О сайте</a>
        </li>
      </ul>
      </strong>
    </div>

    <ul class="nav navbar-nav mx-auto">
        {% if user.is_authenticated %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle mx-4" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  {{ user.username }} 
              </a>
              <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDropdownMenuLink">
                <li><a class="dropdown-item" href="{% url 'accounts:view-profile' username_slug=user.username %}"> Смотреть профиль </a></li>
                <li><a class="dropdown-item" href="{% url 'accounts:edit-profile' username_slug=user.username %}"> Редактировать профиль </a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="{% url 'accounts:logout'  %}"> Выйти </a></li>
              </ul>
            </li>
        {% else %}
            <span class="navbar-text">
                <strong>
                    <a href="{% url 'accounts:registration' %}"> Регистрация </a> | 
                    <a href="{% url 'accounts:login' %}"> Вход </a>
                </strong>
            </span>
        {% endif %}
    </ul>
  </div>
</nav>